#
# Module manifest for module 'AVDHostConfiguration'
#
# Generated by: Kloud Klickers GmbH
#
# Generated on: 2024-10-16
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '12345678-1234-1234-1234-123456789012'

# Author of this module
Author = 'Kloud Klickers GmbH'

# Company or vendor of this module
CompanyName = 'Kloud Klickers GmbH'

# Copyright statement for this module
Copyright = '(c) 2024 Kloud Klickers GmbH. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Azure Machine Configuration for AVD Host setup - replaces DSC Extension functionality with Azure Policy Guest Configuration support'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PSDscResources')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'AVDHostConfiguration.ps1',
    'FSLogixConfiguration.ps1',
    'GPUConfiguration.ps1',
    'StorageAccountAccess.ps1'
)

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @(
    'AVDHostConfiguration',
    'FSLogixConfiguration', 
    'GPUConfiguration',
    'StorageAccountAccess'
)

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @(
    'AVDHostConfiguration.ps1',
    'FSLogixConfiguration.ps1',
    'GPUConfiguration.ps1',
    'StorageAccountAccess.ps1',
    'metadata.json',
    'README.md',
    'AVDHostConfiguration.psd1',
    'Policies/avd-host-configuration-policy.json',
    'Scripts/Install-AVDAgent.ps1',
    'Scripts/install-avd-agent-arm-template.json',
    'Tests/Configuration.Tests.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DSC', 'AzureMachineConfiguration', 'AVD', 'FSLogix', 'GPU', 'Azure', 'Policy', 'GuestConfiguration')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/kloud-klickers-gmbh/kk-dsc-extensions/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/kloud-klickers-gmbh/kk-dsc-extensions'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
# Version 1.0.0

Initial release of Azure Machine Configuration module for AVD hosts.

## Features
- FSLogix profile configuration via registry settings
- GPU acceleration policies for RDS/AVD
- Storage account access configuration via cmdkey
- Azure Policy integration for compliance monitoring
- Drift detection and automatic remediation

## Migration from DSC Extension
This module replaces the functionality previously provided by KK-DSC-AVD.ps1 DSC Extension:
- Converted to use PSDscResources instead of custom modules
- Separated installation tasks (AVD Agent, Domain Join) to appropriate solutions
- Added Azure Policy support for continuous monitoring
- Improved error handling and logging

## Breaking Changes
- AVD Agent installation moved to Custom Script Extension
- Domain Join operations moved to Azure AD Join or separate ARM templates
- Reboot handling now managed by Azure Machine Configuration automatically

## Requirements
- PowerShell 5.1 or later
- PSDscResources module
- Azure Policy Guest Configuration extension on target VMs
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        ExternalModuleDependencies = @('PSDscResources')

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}